# Generated by Django 4.1.7 on 2023-06-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakeryApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakerycards',
            name='image',
            field=models.TextField(default='', max_length=600),
        ),
    ]
